### ISSUE TITLE
Privacy-invasive RPCs

### ISSUE THREAD

**Issue by extemporary** [brumewallet/wallet#22]
Tenderly's RPC, which is [used by default](https://github.com/brumewallet/wallet/blob/f5ddeaf7d56a36bf041a2086af69e2ec4bffa11a/src/libs/ethereum/mods/chain.tsx#L19), does not respect user privacy, stating [they are likely to collect and store transactional data and information](https://chainlist.org/). Please remove or replace it with more privacy-respecting alternatives listed there on Chainlist, especially as we can not set custom RPCs ourselves.

**Comment by hazae41** [comment]
This is a likely a non-issue, they don't have your IP, the only data they can collect is already public anyway (wallet address, amounts, tokens you use)

**Comment by hazae41** [comment]
> Does this take known and unknown IP-independent user fingerprinting techniques, like https://x.com/SCBuergel/status/1798031499318706484, into account?

This is independent of anything that happens on dapps because we can't control them

Brume provides its Tor-proxied RPC to dapps via `window.ethereum` and EIP-6963, which they can choose to use or not

We can't prevent them from using another RPC, or from sending all your data to their own servers or advertisers

Whether you use private RPC or not, Brume or not, if you use a dapp that sucks at privacy, your privacy is doomed

This "discovery" is not a real one and is just made for shilling a more centralized Tor competitor

> Regardless, I'd have to disagree as a matter of "defense-in-depth". It also doesn't make sense to patronise, thus add to the market-share of, a privacy-invasive option when so many less bad alternatives seem to exist.

Sure, I can add private RPCs if they are as reliable and popular as the unprivate ones, the more RPC we have as a backup the better it is, but I can't remove unprivate ones until we have a sufficient amount of private ones that are reliable and independents

Keep in mind that adding unpopular private RPCs is double-edged because when you use unpopular RPCs, your anonymity set decreases, both from the network perspective (your IP contacting this specific RPC), but also if that unpopular private RPC is in fact a honeypot that collects all wallets and IPs

So in the "defense-in-depth" case where Tor fails and the RPC is a honeypot, you have given your wallet and IP to a low anonymity set and your privacy is doomed

**Comment by hazae41** [comment]
So if you have reliable, popular, and private RPCs in mind that do not block Tor, let's add them, otherwise it's better not to touch anything

The ones I included have been battle-tested for months as reliable and are popular among other apps

**Comment by hazae41** [comment]
I know Chainlist, most RPCs there are unreliable, block Tor, or are unpopular

**Comment by hazae41** [comment]
I remember having tried all RPCs for all chains

I even used llamarpc in previous versions, as it did not block Tor, but it was unstable so I removed it

Maybe it changed so I will retry again for the most popular ones

**Comment by hazae41** [comment]
Keep in mind we do not use RPCs like other apps

We send many requests at once and expect the responses to be the same as the other RPCs in order to reject lies

So a RPC that works fine on a normal dapp may not work fine via Tor, and it may be even worse via Brume
