### ISSUE TITLE
Clarify security of entry-point of Snowflake servers

### ISSUE THREAD

**Issue by paulmillr** [brumewallet/wallet#27]
1. Brume always makes all requests using Snowflake entry nodes. Can snowflake server log and correlate all requests by particular users?
2. How would a user adjust address of the snowflake entry node?

**Comment by hazae41** [comment]
1. I don't think so, they only have your IP and since the anonymity set is basically all Tor Snowflake users + all Brume users, they can't do much even with timing, Brume is ~200 daily users, and most of them are passive so looking at the blockchain won't help

2. Cannot be done for now, maybe in the future you will be able to set it, but it's a UX nightmare as it starts connecting on start to make the app work, and has to work independently of user profiles, I also have plans to decentralize it using a network

**Comment by paulmillr** [comment]
So, to clarify, ALL 200 brume users are using one single snowflake server?

**Comment by hazae41** [comment]
Yes

**Comment by paulmillr** [comment]
Makes this server an easy target for eavesdropping.

Anonymity set would be massively reduced to people connecting to this server.

**Comment by paulmillr** [comment]
> Did you know that Snowflake proxies are operated entirely by volunteers? In other words, a user gets matched with a random Snowflake volunteer proxy, which is run by a volunteer like you! So, if you want to help people bypass censorship, consider installing and running a Snowflake proxy. The only prerequisite is that the Internet in your country is not heavily censored already.

**Comment by paulmillr** [comment]
From snowflake website:

>Did you know that Snowflake proxies are operated entirely by volunteers? In other words, a user gets matched with a random Snowflake volunteer proxy, which is run by a volunteer like you! So, if you want to help people bypass censorship, consider installing and running a Snowflake proxy. The only prerequisite is that the Internet in your country is not heavily censored already.

So, in their implementation, it's always "random snowflake node". In Brume, it's always one single snowflake server. Which makes Brume server an easy target for eavesdropping.

Anonymity set would be reduced to people using this particular server. Which is a big deal. So this is not really a "tor-enabled wallet". This is a proxied-through-one-node-to-tor wallet.

**Comment by hazae41** [comment]
Yes, working on it
